### ISSUE TITLE
Ich bin Prozessanalyst und möchte den "richtigen" Zeitpunkt in einem Projekt für die Modellierung von Prozessen finden

### ISSUE THREAD

**Issue by ArminAtGitHub** [pcg-platinus/feedback#8]
Bei uns werden in Projekten oft Prozesse in Visio gezeichnet, weil man auf unterster (meist manueller oder sogar applikatorischer) Ebene den GESAMTEN Prozess sehen möchte.
In Repositories wie Adonis wären hier für alle Beteiligte entsprechende Read&Explore-Lizenzen notwendig, die man sich (inklusive der Aufwände wie Schulungen) sparen möchte und das Designen einer Zeichnung einfacher ist als einer objektorientierten Datenbank (mit ihren Modellierungs- und Objektablage-Guidelines).

Ist es klug, bis zur Abnahme durch den Kunden damit zu warten und dann erst den fertigen Prozess zu übertragen (also am Ende des Prozessschrittes, in dem das To-Be erstellt wird) und ihn in die richtigen Haupt-/Subprozesse zu schneiden?

Zu welchem Zeitpunkt sollte man spätestens die Visio-Prozesse ins Adonis übertragen?

**Comment by chris-tipotsch-platinus** [comment]
## Antwort
Für die Modellierung von Prozessdiagrammen sind IT-Services bzw. Applikationen sinnvoll. Das Lizenzproblem ist mir bekannt. 
Wenn also keine SW zum Zeitpunkt von Entwürfen zur Verfügung steht, greifen Prozessmitarbeiter gerne auf verfügbare Boardmittel u.a oft MS Visio oder https://bpmn.io/ zurück, um Prozessdiagramme zu skiziieren. Dabei sind den meisten Modellerstellern die Abhängigkeiten zu an Modellobjekten wie Rollen, Dolumenten, Informationssystemen nicht beeusst und meist auch nicht bekannt. 

Daher sollte der folgende  Schritt bedacht werden

1. "Awareness" schaffen zu Modellierungskonventionen und Abhängigkeiten --> BPM-Foundation Schulung.
2. BPM-Dienstlesitung der Modellierung offerieren. Nach dem Grundssatz. "Do it right the fist time".
3. Dokumentation ist ein Bestandteil von Prozessdesigns. Daher gleich die Rolle des Proezssmodellieres einbinden. 

Es ist daher nicht klug bis zur Abnahme von Visio-Diagrammen zu warten:
Es ist ratsam gleich zu Beginn mitzuarbeiten und die BPM-Fähigkeiten gezielt zu entwicklen.

**Comment by chris-tipotsch-platinus** [comment]
Tel an Armin.
